export default products = [
    {
        id : '1',
        name : 'Precia Gemstone Necklace NEPRNGTRCKY014',
        productCode :'NEPRNGTRCKY014',
        price : 392443,
        description : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. ",
        category : 'Necklace',
        Image : require('../assets/cartItems/item2.jpg'),
        gender : 'Female',
        goldPurity : '22 KT (916)',
        grossWeight : '60.7400 gram',
        netWeight : '53.7500 gram',
        certificationDetails : ['BIS Hallmark 916', , 'Test'],
        availability : true,
    },
    {
        id : '2',
        name : 'Precia Gemstone Necklace NEPRNGTRCKY014',
        productCode :'NEPRNGTRCKY014',
        price : 392443,
        description : '',
        category : 'Necklace',
        Image : require('../assets/cartItems/item2.jpg'),
        gender : 'Female',
        goldPurity : '22 KT (916)',
        grossWeight : '60.7400 gram',
        netWeight : '53.7500 gram',
        certificationDetails : ['BIS Hallmark 916'],
        availability : true,
    },    
    {
        id : '3',
        name : 'Precia Gemstone Necklace NEPRNGTRCKY014',
        productCode :'NEPRNGTRCKY014',
        price : 392443,
        description : '',
        category : 'Necklace',
        Image : require('../assets/cartItems/item2.jpg'),
        gender : 'Female',
        goldPurity : '22 KT (916)',
        grossWeight : '60.7400 gram',
        netWeight : '53.7500 gram',
        certificationDetails : ['BIS Hallmark 916'],
        availability : true,
    },    
    {
        id : '4',
        name : 'Precia Gemstone Necklace NEPRNGTRCKY014',
        productCode :'NEPRNGTRCKY014',
        price : 392443,
        description : '',
        category : 'Necklace',
        Image : require('../assets/cartItems/item2.jpg'),
        gender : 'Female',
        goldPurity : '22 KT (916)',
        grossWeight : '60.7400 gram',
        netWeight : '53.7500 gram',
        certificationDetails : ['BIS Hallmark 916'],
        availability : true,
    },
    {
        id : '5',
        name : 'Precia Gemstone Necklace NEPRNGTRCKY014',
        productCode :'NEPRNGTRCKY014',
        price : 392443,
        description : '',
        category : 'Necklace',
        Image : require('../assets/cartItems/item2.jpg'),
        gender : 'Female',
        goldPurity : '22 KT (916)',
        grossWeight : '60.7400 gram',
        netWeight : '53.7500 gram',
        certificationDetails : ['BIS Hallmark 916'],
        availability : true,
    },
    {
        id : '6',
        name : 'Precia Gemstone Necklace NEPRNGTRCKY014',
        productCode :'NEPRNGTRCKY014',
        price : 392443,
        description : '',
        category : 'Necklace',
        Image : require('../assets/cartItems/item2.jpg'),
        gender : 'Female',
        goldPurity : '22 KT (916)',
        grossWeight : '60.7400 gram',
        netWeight : '53.7500 gram',
        certificationDetails : ['BIS Hallmark 916'],
        availability : true,
    },
    {
        id : '7',
        name : 'Precia Gemstone Necklace NEPRNGTRCKY014',
        productCode :'NEPRNGTRCKY014',
        price : 392443,
        description : '',
        category : 'Necklace',
        Image : require('../assets/cartItems/item2.jpg'),
        gender : 'Female',
        goldPurity : '22 KT (916)',
        grossWeight : '60.7400 gram',
        netWeight : '53.7500 gram',
        certificationDetails : ['BIS Hallmark 916'],
        availability : true,
    },

]; 