import products from './TempProductData';
export default stores = [
    {   
        id :'1',
        name : 'MALABAR GOLD AND DIAMONDS',
        smalldescription : '',
        image : require("../assets/Shop/malabar.jpg"),
        products : [...products],
        location : '',
        email : '',
        phone : '789045673',
        address : '',
        pincode : '674839',
        rating : 4.5,
        deliveryCost : 50.00,
    },    {   
        id :'2',
        name : 'MALABAR GOLD AND DIAMONDS',
        smalldescription : '',
        image : require("../assets/Shop/malabar.jpg"),
        products : [...products],
        location : '',
        email : '',
        phone : '789045673',
        address : '',
        pincode : '674839',
        rating : 4.5,
        deliveryCost : 50.00,
    },
    {   
        id :'3',
        name : 'MALABAR GOLD AND DIAMONDS',
        smalldescription : '',
        image : require("../assets/Shop/malabar.jpg"),
        products : [...products],
        location : '',
        email : '',
        phone : '789045673',
        address : '',
        pincode : '674839',
        rating : 4.5,
        deliveryCost : 50.00,
    },
]